### ISSUE TITLE
when 2019

### ISSUE THREAD

**Issue by bigpod98** [swdotcom/swdc-visualstudio#2]
when will you sllow for 2019

**Comment by dubbe** [comment]
I did a quick and perhaps dirty fix, you can find the sourcode here: https://github.com/dubbe/swdc-visualstudio if you wan't to try it out.

**Comment by SteinTheRuler** [comment]
yes, when can we expect a VS 2019 compatible version?

**Comment by xavluiz** [comment]
We are now compatible for vs 2019 as of v2.3.8. Please let us know if there are any issues.

**Comment by SteinTheRuler** [comment]
still the same error - VS 2019 stops completely. the output window changes to Code Time and stops completely without any output. works fine in VS Code.
