### ISSUE TITLE
Keep getting this error message when trying to use it

### ISSUE THREAD

**Issue by santhosh3000** [swdotcom/swdc-visualstudio#4]
I'm using Visual Studio Community v15.09.10. I tried uninstalling Code Time and VSC and I still get this error. It was working previously, but I cant figure out why its not working anymore. 

![2019-03-30 00_15_59-Microsoft Visual Studio](https://user-images.githubusercontent.com/33672419/55271318-747b3080-5281-11e9-97d1-5c8c51055f0c.png)
![2019-03-30 00_17_38-Microsoft Edge](https://user-images.githubusercontent.com/33672419/55271319-747b3080-5281-11e9-93c7-d093b12cfcf1.png)
Here are a list of my extension, maybe one of them are conflicting with it? 
![2019-03-30 00_22_00-Extensions and Updates](https://user-images.githubusercontent.com/33672419/55271368-0c791a00-5282-11e9-80ce-831003da09c9.png)

**Comment by brettmstevens7** [comment]
@santhosh3000 we pushed a fix that should hopefully take care of this issue. Would you be able to reinstall and try again? If you encounter the same error when you reinstall, we've also added a log file that you can send us -- it'll be in your .software folder in your root user directory. 

We'll send you a Cody t-shirt if you could help us with this... thanks in advance!

**Comment by santhosh3000** [comment]
@brettmstevens7 yes, its working for me. Thanks

**Comment by roshtov6** [comment]
Hi,
I've installed the latest version ( 2.3.8 ) on Visual Studio 19 and I'm experiencing the same issue.
Any Ideas?
BTW couldn't find the log file you mentioned but attached is the ActivityLog.xml that was specified on the error message,
[ActivityLog.xml.txt](https://github.com/swdotcom/swdc-visualstudio/files/5278644/ActivityLog.xml.txt)
